version: '3.8'
services:
 docker-react-dev:
  image: react-docker-dev-ima
  build:
   dockerfile: Dockerfile.dev
  container_name: react-docker-dev-c
  ports:
   - "8080:3000"
  environment:
    - NODE_ENV=development